//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subtask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subtask()
        {
            this.MemberSubtask = new HashSet<MemberSubtask>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Specification { get; set; }
        public System.DateTime DateOfStart { get; set; }
        public Nullable<System.DateTime> DateOfEnd { get; set; }
        public int IdStatus { get; set; }
        public int IdTask { get; set; }
        public string Comments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberSubtask> MemberSubtask { get; set; }
        public virtual Status Status { get; set; }
        public virtual Task Task { get; set; }
    }
}
