//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_Manager
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserHistory
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdAction { get; set; }
        public System.DateTime DateAction { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual User User { get; set; }
    }
}
